from sqlalchemy.orm import Session

from app.db.models import (
    CategoryModel,
    OrgSearchProfileModel,
    OrganizationModel,
    PurchaseHistoryModel,
    SearchEventModel,
    SearchSessionModel,
    STEItemModel,
    SpellCorrectionModel,
    SupplierModel,
    SynonymModel,
    UserModel,
    UserSearchProfileModel,
)


def _merge_all(session: Session, rows: list[object]) -> None:
    for row in rows:
        session.merge(row)
    session.commit()


def seed_demo_data(session: Session) -> None:
    _merge_all(
        session,
        [
            OrganizationModel(id="org_1", name="Демо-организация"),
            OrganizationModel(id="org_2", name="Департамент цифровых сервисов"),
            CategoryModel(id="cat_transport", name="Транспорт"),
            CategoryModel(id="cat_it", name="ИТ и оборудование"),
            CategoryModel(id="cat_service", name="Услуги"),
            CategoryModel(id="cat_office", name="Офис и снабжение"),
            SupplierModel(id="sup_1", name='ООО "Городской транспорт"'),
            SupplierModel(id="sup_2", name='ООО "ИнфоСистемы"'),
            SupplierModel(id="sup_3", name='ООО "Сервис плюс"'),
            SupplierModel(id="sup_4", name='ООО "МосСнаб"'),
        ],
    )

    _merge_all(
        session,
        [
            UserModel(
                id="user_1",
                organization_id="org_1",
                name="Демо-пользователь",
                role="customer",
            ),
            UserModel(
                id="user_2",
                organization_id="org_2",
                name="Специалист закупок",
                role="customer",
            ),
            STEItemModel(
                id="ste_101",
                title="Аренда автобуса для перевозки детей",
                description="Услуга аренды автобуса с водителем.",
                category_id="cat_transport",
                supplier_id="sup_1",
                attributes_json={"vehicle": "автобус", "audience": "дети"},
                status="active",
            ),
            STEItemModel(
                id="ste_102",
                title="Поставка серверного оборудования",
                description="Серверы для городской ИТ-инфраструктуры.",
                category_id="cat_it",
                supplier_id="sup_2",
                attributes_json={"type": "server", "format": "tower"},
                status="active",
            ),
            STEItemModel(
                id="ste_103",
                title="Техническое сопровождение информационной системы",
                description="Поддержка и сопровождение информационных систем.",
                category_id="cat_service",
                supplier_id="sup_3",
                attributes_json={"service": "support", "subject": "system"},
                status="active",
            ),
            STEItemModel(
                id="ste_104",
                title="Аренда микроавтобуса для пассажирских перевозок",
                description="Транспортная услуга для перевозки групп и делегаций.",
                category_id="cat_transport",
                supplier_id="sup_1",
                attributes_json={"vehicle": "микроавтобус", "purpose": "перевозка"},
                status="active",
            ),
            STEItemModel(
                id="ste_105",
                title="Поставка ноутбуков и рабочих станций",
                description="Компьютерная техника для рабочих мест сотрудников.",
                category_id="cat_it",
                supplier_id="sup_2",
                attributes_json={"type": "laptop", "class": "workstation"},
                status="active",
            ),
            STEItemModel(
                id="ste_106",
                title="Обслуживание серверной инфраструктуры",
                description="Услуги администрирования и мониторинга серверов.",
                category_id="cat_service",
                supplier_id="sup_3",
                attributes_json={"service": "admin", "subject": "servers"},
                status="active",
            ),
            STEItemModel(
                id="ste_107",
                title="Поставка офисной бумаги и канцелярских товаров",
                description="Расходные материалы для административных подразделений.",
                category_id="cat_office",
                supplier_id="sup_4",
                attributes_json={"type": "paper", "group": "stationery"},
                status="active",
            ),
            STEItemModel(
                id="ste_108",
                title="Аренда автобуса для общего использования",
                description="Автобусные перевозки сотрудников и делегаций.",
                category_id="cat_transport",
                supplier_id="sup_1",
                attributes_json={"vehicle": "автобус", "purpose": "general"},
                status="active",
            ),
            STEItemModel(
                id="ste_109",
                title="Поставка стоечных серверов для дата-центра",
                description="Серверные стойки и вычислительные узлы для ЦОД.",
                category_id="cat_it",
                supplier_id="sup_2",
                attributes_json={"type": "server", "format": "rack"},
                status="active",
            ),
            STEItemModel(
                id="ste_110",
                title="Поставка сетевых коммутаторов и маршрутизаторов",
                description="Сетевое оборудование для узлов связи и серверных помещений.",
                category_id="cat_it",
                supplier_id="sup_2",
                attributes_json={"type": "network", "group": "switch"},
                status="active",
            ),
            STEItemModel(
                id="ste_111",
                title="Услуги клининга административных помещений",
                description="Ежедневная уборка офисов, холлов и общих зон.",
                category_id="cat_service",
                supplier_id="sup_3",
                attributes_json={"service": "cleaning", "object": "office"},
                status="active",
            ),
            STEItemModel(
                id="ste_112",
                title="Комплексное обслуживание офисных помещений",
                description="Эксплуатация, мелкий ремонт и обеспечение офисной инфраструктуры.",
                category_id="cat_service",
                supplier_id="sup_3",
                attributes_json={"service": "facility", "object": "office"},
                status="active",
            ),
            STEItemModel(
                id="ste_113",
                title="Поставка картриджей и расходных материалов для печати",
                description="Тонеры, картриджи и расходники для офисной оргтехники.",
                category_id="cat_office",
                supplier_id="sup_4",
                attributes_json={"type": "cartridge", "group": "printing"},
                status="active",
            ),
            STEItemModel(
                id="ste_114",
                title="Поставка офисных кресел и рабочих столов",
                description="Мебель для оснащения рабочих мест сотрудников.",
                category_id="cat_office",
                supplier_id="sup_4",
                attributes_json={"type": "furniture", "group": "office"},
                status="active",
            ),
            STEItemModel(
                id="ste_115",
                title="Техническая поддержка ноутбуков и рабочих мест",
                description="Выездное и удаленное обслуживание пользовательской техники.",
                category_id="cat_service",
                supplier_id="sup_3",
                attributes_json={"service": "support", "subject": "workplaces"},
                status="active",
            ),
            SynonymModel(
                id="syn_1",
                term="автобус",
                synonym="пассажирский транспорт",
                weight="1.0",
                source="manual",
            ),
            SynonymModel(
                id="syn_2",
                term="сервер",
                synonym="серверное оборудование",
                weight="1.0",
                source="manual",
            ),
            SynonymModel(
                id="syn_3",
                term="ноутбук",
                synonym="рабочая станция",
                weight="0.7",
                source="manual",
            ),
            SynonymModel(
                id="syn_4",
                term="бумага",
                synonym="канцелярские товары",
                weight="0.8",
                source="manual",
            ),
            SynonymModel(
                id="syn_5",
                term="клининг",
                synonym="уборка помещений",
                weight="1.0",
                source="manual",
            ),
            SynonymModel(
                id="syn_6",
                term="офис",
                synonym="рабочее место",
                weight="0.6",
                source="manual",
            ),
            SynonymModel(
                id="syn_7",
                term="канцелярия",
                synonym="канцтовары",
                weight="1.0",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_1",
                wrong_term="абтобус",
                correct_term="автобус",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_2",
                wrong_term="серверноое",
                correct_term="серверное",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_3",
                wrong_term="ноутубк",
                correct_term="ноутбук",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_4",
                wrong_term="бумга",
                correct_term="бумага",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_5",
                wrong_term="клиннинг",
                correct_term="клининг",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_6",
                wrong_term="канцеляря",
                correct_term="канцелярия",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_7",
                wrong_term="афтобус",
                correct_term="автобус",
                source="manual",
            ),
            SpellCorrectionModel(
                id="spell_8",
                wrong_term="принтэр",
                correct_term="принтер",
                source="manual",
            ),
        ],
    )

    _merge_all(
        session,
        [
            UserSearchProfileModel(
                user_id="user_1",
                organization_id="org_1",
                top_categories_json=["Транспорт", "Услуги", "Офис и снабжение"],
                recent_ste_ids_json=["ste_101", "ste_108", "ste_111"],
                top_suppliers_json=['ООО "Городской транспорт"', 'ООО "Сервис плюс"'],
                popular_queries_json=[
                    "автобус",
                    "перевозка детей",
                    "аренда транспорта",
                    "пассажирский транспорт",
                    "клининг",
                    "бумага",
                ],
            ),
            UserSearchProfileModel(
                user_id="user_2",
                organization_id="org_2",
                top_categories_json=["ИТ и оборудование", "Услуги"],
                recent_ste_ids_json=["ste_102", "ste_106", "ste_109"],
                top_suppliers_json=['ООО "ИнфоСистемы"', 'ООО "Сервис плюс"'],
                popular_queries_json=[
                    "сервер",
                    "обслуживание серверов",
                    "рабочие станции",
                    "коммутатор",
                    "ноутбук",
                ],
            ),
            OrgSearchProfileModel(
                organization_id="org_1",
                top_categories_json=["Транспорт", "Услуги", "Офис и снабжение"],
                popular_ste_ids_json=["ste_101", "ste_108", "ste_104", "ste_111", "ste_107"],
            ),
            OrgSearchProfileModel(
                organization_id="org_2",
                top_categories_json=["ИТ и оборудование", "Услуги"],
                popular_ste_ids_json=["ste_102", "ste_106", "ste_105", "ste_109", "ste_110"],
            ),
            PurchaseHistoryModel(
                id="ph_1",
                user_id="user_1",
                organization_id="org_1",
                ste_id="ste_101",
                quantity="2",
                price="320000",
            ),
            PurchaseHistoryModel(
                id="ph_2",
                user_id="user_1",
                organization_id="org_1",
                ste_id="ste_108",
                quantity="1",
                price="180000",
            ),
            PurchaseHistoryModel(
                id="ph_3",
                user_id="user_1",
                organization_id="org_1",
                ste_id="ste_111",
                quantity="12",
                price="540000",
            ),
            PurchaseHistoryModel(
                id="ph_4",
                user_id="user_1",
                organization_id="org_1",
                ste_id="ste_107",
                quantity="30",
                price="125000",
            ),
            PurchaseHistoryModel(
                id="ph_5",
                user_id="user_2",
                organization_id="org_2",
                ste_id="ste_102",
                quantity="4",
                price="2450000",
            ),
            PurchaseHistoryModel(
                id="ph_6",
                user_id="user_2",
                organization_id="org_2",
                ste_id="ste_106",
                quantity="1",
                price="610000",
            ),
            PurchaseHistoryModel(
                id="ph_7",
                user_id="user_2",
                organization_id="org_2",
                ste_id="ste_109",
                quantity="2",
                price="1760000",
            ),
        ],
    )

    _merge_all(
        session,
        [
            SearchSessionModel(
                id="session_1",
                user_id="user_1",
                organization_id="org_1",
                query="автобус для детей",
                normalized_query="автобус для детей",
            ),
            SearchSessionModel(
                id="session_2",
                user_id="user_2",
                organization_id="org_2",
                query="сервер",
                normalized_query="сервер",
            ),
            SearchSessionModel(
                id="session_3",
                user_id="user_1",
                organization_id="org_1",
                query="клининг",
                normalized_query="клининг",
            ),
            SearchSessionModel(
                id="session_4",
                user_id="user_1",
                organization_id="org_1",
                query="бумага",
                normalized_query="бумага",
            ),
        ],
    )

    _merge_all(
        session,
        [
            SearchEventModel(
                id="event_seed_1",
                session_id="session_1",
                user_id="user_1",
                organization_id="org_1",
                event_type="result_clicked",
                ste_id="ste_101",
                payload_json={"position": 1},
            ),
            SearchEventModel(
                id="event_seed_2",
                session_id="session_1",
                user_id="user_1",
                organization_id="org_1",
                event_type="favorite_added",
                ste_id="ste_108",
                payload_json={"source": "search"},
            ),
            SearchEventModel(
                id="event_seed_3",
                session_id="session_2",
                user_id="user_2",
                organization_id="org_2",
                event_type="result_opened",
                ste_id="ste_102",
                payload_json={"position": 1},
            ),
            SearchEventModel(
                id="event_seed_4",
                session_id="session_3",
                user_id="user_1",
                organization_id="org_1",
                event_type="result_clicked",
                ste_id="ste_111",
                payload_json={"position": 1},
            ),
        ],
    )
